### ISSUE TITLE
AddCustomAttributes doesn't work in the app.ErrorHandler

### ISSUE THREAD

**Issue by daenney** [samber/slog-fiber#13]
I have a custom error handler. In it I do a simple `slogfiber.AddCustomAttributes()` so I can hopefully add the error itself to the log message. However, none of the attributes added in the error handler ever make it into the output.

```go
func apiErrorHandler(ctx *fiber.Ctx, err error) error {
	slogfiber.AddCustomAttributes(ctx, slog.String("hi", "there"))

	var e *fiber.Error
	code := fiber.StatusInternalServerError
	if errors.As(err, &e) {
		code = e.Code
	}

	return ctx.Status(code).JSON(...)
}
```

The `hi` key with value `there` is always missing, and so is any other attribute added in the error handler.

**Comment by samber** [comment]
It works when i test with this function. Can you please create a small repository with a short example?

**Comment by daenney** [comment]
Also, on closer inspection the `status` in the log line isn't correct either. If I print the value of `code` in the handler, I get a 404. But I consistently get `status=200` in the log line.

**Comment by samber** [comment]
About the 404 error, you should add a "catch-all" handler:

```go
        // ...

	app.Use(slogfiber.NewWithConfig(logger, config))
	app.Use("/found", func(ctx *fiber.Ctx) error {
		return ctx.SendString("found it")
	})

	// Last handler
	app.Use(func(c *fiber.Ctx) error {
		return c.SendStatus(fiber.StatusNotFound)
	})

	app.Listen(":1111")
```

**Comment by samber** [comment]
We might think about doing both a middleware and error handler.

**Comment by samber** [comment]
hi @daenney 

I just made a proposal here: #14

**Comment by daenney** [comment]
Ah brilliant, I will take a look!

**Comment by samber** [comment]
After the merge of #19 this should be fixed.

Can you check and return it to me if it's not working well?
