### ISSUE TITLE
kong logs

### ISSUE THREAD

**Issue by wade-liwei** [samber/slog-fiber#20]
Do you have an example of logging a Kong proxy log?

If I run the fiber web service with slog-fiver (default param) + kong proxy, it will work ok.
If I run the fiber web service with slog-fiver (following param) + kong proxy, it will not work ok.

	cfg := slogfiber.Config{
		WithUserAgent:      true,
		WithRequestID:      true,
		WithRequestBody:    true,
		WithRequestHeader:  true,
		WithResponseBody:   true,
		WithResponseHeader: true,
		WithSpanID:         true,
		WithTraceID:        true,
		DefaultLevel:     slog.LevelInfo,
		ClientErrorLevel: slog.LevelWarn,
		ServerErrorLevel: slog.LevelError,
	}

**Comment by samber** [comment]
Can you explain the error ?

Your message is not very helpful.

**Comment by wade-liwei** [comment]
I did not find any errors.
Could you please help me to find the errors?

**Comment by wade-liwei** [comment]
If I enable the parameter  "WithRequestHeader:  true, " with kong proxy, then I will can not get the log.

I guess kong with not standard http headers.

**Comment by wade-liwei** [comment]
Yea, 
If I run the fiber web service with slog-fiver (default param) + kong proxy, it will work ok.
If I run the fiber web service with slog-fiver (following param) + kong proxy, it will not work ok.

cfg := slogfiber.Config{
	WithUserAgent:      true,
	WithRequestID:      true,
	WithRequestBody:    true,
	WithRequestHeader:  true,
	WithResponseBody:   true,
	WithResponseHeader: true,
	WithSpanID:         true,
	WithTraceID:        true,
	DefaultLevel:     slog.LevelInfo,
	ClientErrorLevel: slog.LevelWarn,
	ServerErrorLevel: slog.LevelError,
}

If I run the fiber web service with slog-fiver, it will work ok.

**Comment by samber** [comment]
You did not reply to my questoin.

**Comment by wade-liwei** [comment]
Did you try to bypass kong and reach the HTTP service directly, in order to test the logger?


yea, if   bypass kong and reach the HTTP service directly.  no problem.

**Comment by samber** [comment]
can you provide a repository to reproduce the error?

**Comment by wade-liwei** [comment]
I  found out the problem is Loki http rate limit,
Thank you, good man.
