### ISSUE TITLE
error fiber v3 using

### ISSUE THREAD

**Issue by Phandorin** [samber/slog-fiber#21]
fiber v3 handler does not use pointer in new handler function:

panic: use: invalid handler func(*fiber.Ctx) error

Do you fix this in nearest time?
Thank you!

**Comment by samber** [comment]
Hi @Phandorin 

Can you start a "fiber-v3" branch please and make changes?

**Comment by githugt** [comment]
Seeing as a tag isn't yet created for this, do you want to create that tag or delete this

```
# Fiber v3 (beta)
go get github.com/samber/slog-echo@fiber-v3
```
from the readme.md ?

Because, currently, running 
```
go get github.com/samber/slog-echo@fiber-v3
```
And `github.com/samber/slog-fiber` would fail with invalid handler if they use v3 version of fiber.

**Comment by samber** [comment]
The right command is:

```sh
go get github.com/samber/slog-echo@fiber-v3
```

Sorry for the issue.
