### ISSUE TITLE
Is it possible to add custom attrs from fiber context?

### ISSUE THREAD

**Issue by stavros-k** [samber/slog-fiber#6]
For example request/response body or request ID.

Currently there is request id being added (that can be disabled).
What if I want to use the request ID middleware, in order to use a custom header / generator.
How I could log that?

Thanks!

**Comment by samber** [comment]
I suppose we can do something like that:

```go
slogfiber.NewWithConfig(
    logger,
    slogfiber.Config{
        CustomAttrs: func (ctx *fiber.Ctx) []slog.Attr {
              .......
        },
        WithRequestBody: bool,
        WithResponseBody: bool,
    },
)
```

WDYT ?

**Comment by stavros-k** [comment]
Looks good yea

**Comment by samber** [comment]
Added to v1.5.0 (see readme).
